<?php
namespace Modules\PriyasaCore\Services;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Modules\PriyasaCore\Models\{Customer,Wallet,LoyaltyAccount,Referral};
use RuntimeException;
final class CustomerGrowthService {
 public function account(Customer $c): array { $w=Wallet::firstOrCreate(['customer_id'=>$c->id],['balance'=>0]);$l=LoyaltyAccount::firstOrCreate(['customer_id'=>$c->id],['points'=>0,'tier'=>'member']);return ['customer_id'=>$c->id,'wallet'=>['balance'=>(float)$w->balance],'loyalty'=>['points'=>(int)$l->points,'tier'=>$l->tier],'referral_code'=>$c->referral_code]; }
 public function walletCredit(Customer $c,float $amount,string $key,string $type='credit',array $meta=[]): array { if($amount<=0)throw new RuntimeException('Amount must be positive.'); return DB::connection('priyasa')->transaction(function()use($c,$amount,$key,$type,$meta){$w=Wallet::where('customer_id',$c->id)->lockForUpdate()->first()??Wallet::create(['customer_id'=>$c->id,'balance'=>0]);$existing=$w->transactions()->where('idempotency_key',$key)->first();if($existing)return ['balance'=>(float)$existing->balance_after,'transaction_id'=>$existing->id,'duplicate'=>true];$w->balance=(float)$w->balance+$amount;$w->save();$tx=$w->transactions()->create(['customer_id'=>$c->id,'amount'=>$amount,'balance_after'=>$w->balance,'type'=>$type,'idempotency_key'=>$key,'metadata'=>$meta]);return ['balance'=>(float)$w->balance,'transaction_id'=>$tx->id,'duplicate'=>false];}); }
 public function points(Customer $c,int $points,string $key,string $type='earn',array $meta=[]): array { if($points===0)throw new RuntimeException('Points must not be zero.'); return DB::connection('priyasa')->transaction(function()use($c,$points,$key,$type,$meta){$a=LoyaltyAccount::where('customer_id',$c->id)->lockForUpdate()->first()??LoyaltyAccount::create(['customer_id'=>$c->id,'points'=>0,'tier'=>'member']);$existing=$a->transactions()->where('idempotency_key',$key)->first();if($existing)return ['points'=>(int)$existing->balance_after,'transaction_id'=>$existing->id,'duplicate'=>true];$next=(int)$a->points+$points;if($next<0)throw new RuntimeException('Insufficient loyalty points.');$a->points=$next;$a->tier=$next>=10000?'elite':($next>=2500?'plus':'member');$a->save();$tx=$a->transactions()->create(['customer_id'=>$c->id,'points'=>$points,'balance_after'=>$next,'type'=>$type,'idempotency_key'=>$key,'metadata'=>$meta]);return ['points'=>$next,'transaction_id'=>$tx->id,'duplicate'=>false];}); }
 public function referralCode(Customer $c): string { if($c->referral_code)return $c->referral_code; do{$code=strtoupper(Str::random(8));}while(Customer::where('referral_code',$code)->exists());$c->referral_code=$code;$c->save();return $code; }
 public function applyReferral(Customer $referrer,Customer $new): Referral { if($referrer->id===$new->id)throw new RuntimeException('Self referral is not allowed.'); if(Referral::where('referred_customer_id',$new->id)->exists())throw new RuntimeException('Customer already has a referral.');return Referral::create(['referrer_customer_id'=>$referrer->id,'referred_customer_id'=>$new->id,'code'=>$this->referralCode($referrer),'status'=>'pending']); }
}
