<?php
namespace Modules\PriyasaCore\Services;
use Carbon\Carbon; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Schema;
final class FinancialReconciliationService {
 public function overview(Carbon $from, Carbon $to): array { $orders=DB::connection('priyasa')->table('priyasa_orders')->whereBetween('created_at',[$from->startOfDay(),$to->endOfDay()]); $gross=(float)$orders->whereNotIn('status',['cancelled'])->sum('grand_total'); $refunds=Schema::connection('priyasa')->hasTable('priyasa_refunds')?(float)DB::connection('priyasa')->table('priyasa_refunds')->whereBetween('created_at',[$from,$to])->whereIn('status',['processed','completed','refunded'])->sum('amount'):0; $payments=Schema::connection('priyasa')->hasTable('priyasa_payments')?(float)DB::connection('priyasa')->table('priyasa_payments')->whereBetween('created_at',[$from,$to])->whereIn('status',['captured','paid','completed'])->sum('amount'):0; return ['period'=>['from'=>$from->toDateString(),'to'=>$to->toDateString()],'gross_sales'=>round($gross,2),'captured_payments'=>round($payments,2),'refunds'=>round($refunds,2),'net_sales'=>round($gross-$refunds,2),'payment_difference'=>round($payments-($gross-$refunds),2)]; }
 public function daily(Carbon $from, Carbon $to): array { $out=[]; for($d=$from->copy()->startOfDay();$d->lte($to);$d->addDay()){ $o=$this->overview($d,$d); $out[]=['metric_date'=>$d->toDateString(),'gross_sales'=>$o['gross_sales'],'refunds'=>$o['refunds'],'net_sales'=>$o['net_sales'],'payment_difference'=>$o['payment_difference']]; } return $out; }
 public function createRun(string $type,?string $provider,Carbon $from,Carbon $to,array $items=[]): int { return DB::connection('priyasa')->transaction(function()use($type,$provider,$from,$to,$items){$id=DB::connection('priyasa')->table('priyasa_reconciliation_runs')->insertGetId(['type'=>$type,'provider'=>$provider,'period_from'=>$from->toDateString(),'period_to'=>$to->toDateString(),'status'=>'running','metadata'=>json_encode([]),'created_at'=>now(),'updated_at'=>now()]); $expected=0;$providerAmount=0;$matched=0;$mismatch=0; foreach($items as $item){$e=(float)($item['expected_amount']??0);$p=(float)($item['provider_amount']??0);$diff=round($e-$p,2);$status=abs($diff)<0.01?'matched':'mismatch';$matched+= $status==='matched'?1:0;$mismatch+= $status==='mismatch'?1:0;$expected+=$e;$providerAmount+=$p;DB::connection('priyasa')->table('priyasa_reconciliation_items')->insert(['run_id'=>$id,'external_reference'=>$item['external_reference']??null,'internal_type'=>$item['internal_type']??null,'internal_id'=>isset($item['internal_id'])?(string)$item['internal_id']:null,'status'=>$status,'expected_amount'=>$e,'provider_amount'=>$p,'difference_amount'=>$diff,'metadata'=>json_encode($item['metadata']??[]),'created_at'=>now(),'updated_at'=>now()]);} DB::connection('priyasa')->table('priyasa_reconciliation_runs')->where('id',$id)->update(['status'=>'completed','total_items'=>count($items),'matched_items'=>$matched,'mismatched_items'=>$mismatch,'expected_amount'=>$expected,'provider_amount'=>$providerAmount,'difference_amount'=>round($expected-$providerAmount,2),'completed_at'=>now(),'updated_at'=>now()]); return $id; }); }
 public function runs(int $limit=50){return DB::connection('priyasa')->table('priyasa_reconciliation_runs')->latest('id')->limit(min($limit,200))->get();}
 public function runItems(int $runId,int $limit=200){return DB::connection('priyasa')->table('priyasa_reconciliation_items')->where('run_id',$runId)->latest('id')->limit(min($limit,500))->get();}
}
