<?php
declare(strict_types=1);
namespace Modules\PriyasaCore\Services;
use Illuminate\Support\Facades\DB;
use Modules\PriyasaCore\Models\Product;
final class SearchIntelligenceService {
 public function search(string $term, int $limit=20, int $page=1, ?int $userId=null, ?string $sessionId=null): array {
  $term=trim($term); $limit=max(1,min(50,$limit)); $page=max(1,$page); if($term==='') return ['items'=>[],'facets'=>['brands'=>[],'categories'=>[]],'meta'=>['total'=>0,'page'=>$page,'per_page'=>$limit,'query'=>'']];
  $normalized=$this->normalize($term); $tokens=$this->tokens($normalized); $synonyms=$this->synonyms($tokens);
  $base=Product::query()->published()->where(function($q) use($tokens,$synonyms,$normalized){
   $terms=array_values(array_unique(array_merge($tokens,$synonyms,[$normalized])));
   foreach($terms as $i=>$t){$like='%'.addcslashes($t,'%_\\').'%'; $method=$i===0?'where':'orWhere'; $q->{$method}(function($x) use($like,$t){$x->where('name','like',$like)->orWhere('brand','like',$like)->orWhere('search_keywords','like',$like)->orWhere('sku',$t)->orWhere('slug',$t);});}
  });
  $total=(clone $base)->count();
  $brands=(clone $base)->whereNotNull('brand')->where('brand','!=','')->select('brand',DB::connection('priyasa')->raw('count(*) as count'))->groupBy('brand')->orderByDesc('count')->limit(20)->get()->map(fn($x)=>['name'=>$x->brand,'count'=>(int)$x->count])->values()->all();
  $categories=(clone $base)->whereNotNull('category_id')->with('category:id,name,slug')->select('category_id')->groupBy('category_id')->limit(20)->get()->map(fn($x)=>['id'=>$x->category_id,'name'=>$x->category?->name,'slug'=>$x->category?->slug])->values()->all();
  $offset=($page-1)*$limit; $items=(clone $base)->with(['category','media','variants.inventory'])->orderByDesc('merchandising_score')->orderByDesc('is_featured')->orderBy('sort_order')->orderByDesc('id')->offset($offset)->limit($limit)->get();
  DB::connection('priyasa')->table('priyasa_search_queries')->insert(['query'=>$term,'normalized_query'=>$normalized,'user_id'=>$userId,'session_id'=>$sessionId,'result_count'=>$total,'searched_at'=>now()]);
  return ['items'=>$items->map(fn($p)=>$this->canonical($p))->values()->all(),'facets'=>['brands'=>$brands,'categories'=>$categories],'meta'=>['total'=>$total,'page'=>$page,'per_page'=>$limit,'query'=>$term,'pages'=>(int)ceil($total/max(1,$limit))]];
 }
 public function suggestions(string $term,int $limit=8): array { $term=$this->normalize($term); if(strlen($term)<2)return []; $like=addcslashes($term,'%_\\').'%'; return Product::query()->published()->where(fn($q)=>$q->where('name','like',$like)->orWhere('brand','like',$like)->orWhere('search_keywords','like',$like))->orderByDesc('is_featured')->orderByDesc('merchandising_score')->limit(max(1,min(20,$limit)))->get(['id','name','slug','brand'])->toArray(); }
 public function trending(int $limit=12): array { $ids=DB::connection('priyasa')->table('priyasa_customer_events')->whereIn('event_type',['product_view','cart_add','wishlist_add','purchase'])->where('occurred_at','>=',now()->subDays(7))->whereNotNull('product_id')->select('product_id',DB::connection('priyasa')->raw("sum(case when event_type='purchase' then 8 when event_type='cart_add' then 4 when event_type='wishlist_add' then 2 else 1 end) as score"))->groupBy('product_id')->orderByDesc('score')->limit(max(1,min(40,$limit)))->pluck('product_id')->all(); return $this->loadCanonical($ids); }
 public function related(int $productId,string $type='similar',int $limit=12): array { $ids=DB::connection('priyasa')->table('priyasa_product_relations')->where('product_id',$productId)->where('relation_type',$type)->orderByDesc('score')->limit(max(1,min(40,$limit)))->pluck('related_product_id')->all(); if(!$ids && $type==='similar'){ $p=Product::find($productId); if($p){$ids=Product::query()->published()->where('id','!=',$productId)->when($p->category_id,fn($q)=>$q->where('category_id',$p->category_id))->orderByDesc('merchandising_score')->limit($limit)->pluck('id')->all();}} return $this->loadCanonical($ids); }
 public function rebuildRelations(int $days=90): int { $since=now()->subDays(max(1,min(365,$days))); $rows=DB::connection('priyasa')->table('priyasa_customer_events')->whereIn('event_type',['cart_add','purchase'])->where('occurred_at','>=',$since)->whereNotNull('product_id')->get(['user_id','session_id','product_id']); $groups=[]; foreach($rows as $r){$key=$r->user_id?'u:'.$r->user_id:($r->session_id?'s:'.$r->session_id:null); if(!$key)continue; $groups[$key][]=(int)$r->product_id;} $scores=[]; foreach($groups as $products){$products=array_values(array_unique($products)); foreach($products as $a)foreach($products as $b)if($a!==$b){$k="$a:$b";$scores[$k]=($scores[$k]??0)+1;}} $count=0; foreach($scores as $key=>$support){[$a,$b]=array_map('intval',explode(':',$key)); DB::connection('priyasa')->table('priyasa_product_relations')->updateOrInsert(['product_id'=>$a,'related_product_id'=>$b,'relation_type'=>'frequently_bought'],['score'=>(float)$support,'support_count'=>(int)$support,'updated_at'=>now(),'created_at'=>now()]); $count++;} return $count; }
 private function synonyms(array $tokens): array { if(!$tokens)return []; $out=[]; foreach(DB::connection('priyasa')->table('priyasa_search_synonyms')->where('is_active',true)->whereIn('term',$tokens)->get() as $r){$vals=json_decode((string)$r->synonyms,true) ?: []; foreach($vals as $v)$out[]=$this->normalize((string)$v);} return array_values(array_unique($out)); }
 private function normalize(string $s): string { $s=preg_replace('/\\s+/u',' ',trim(mb_strtolower($s))) ?? ''; return mb_substr($s,0,255); }
 private function tokens(string $s): array { return array_values(array_filter(preg_split('/[^\\pL\\pN]+/u',$s) ?: [],fn($x)=>mb_strlen($x)>=2)); }
 private function loadCanonical(array $ids): array { if(!$ids)return []; $rows=Product::query()->published()->whereIn('id',$ids)->with(['category','media','variants.inventory'])->get()->keyBy('id'); return collect($ids)->map(fn($id)=>$rows->get($id))->filter()->map(fn($p)=>$this->canonical($p))->values()->all(); }
 private function canonical($p): array { return $p->toArray(); }
}
