<?php
declare(strict_types=1);
namespace Modules\PriyasaCore\Services;
use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Http; use Illuminate\Support\Str; use Modules\PriyasaCore\Models\{Address,Category,Customer,Inventory,Order,Payment,Product,ProductMedia,ProductVariant}; use RuntimeException;
final class WooCommerceService {
 private function client(): array { $url=rtrim((string)config('priyasacore.woocommerce.store_url'),'/'); $key=(string)config('priyasacore.woocommerce.consumer_key'); $secret=(string)config('priyasacore.woocommerce.consumer_secret'); if($url===''||$key===''||$secret==='') throw new RuntimeException('WooCommerce credentials are incomplete.'); return [Http::withBasicAuth($key,$secret)->acceptJson()->timeout((int)config('priyasacore.woocommerce.timeout',30)), $url.'/wp-json/wc/v3']; }
 private function get(string $path,array $query=[]): array {[$http,$base]=$this->client(); $r=$http->get($base.'/'.$path,$query); if(!$r->successful()) throw new RuntimeException('WooCommerce API failed: HTTP '.$r->status().' '.trim((string)data_get($r->json(),'message',''))); return (array)$r->json();}
 public function test(): array {$this->get('system_status'); return ['connected'=>true];}
 public function syncProductById(int $id): array { $r=$this->get('products/'.$id); [, $new, $v, $m]=$this->upsertProduct($r); return ['created'=>$new,'variants'=>$v,'media'=>$m,'external_id'=>(string)$id]; }
 public function syncProducts(int $maxPages=0,int $perPage=100): array { $created=$updated=$variants=$media=0; for($page=1;;$page++){if($maxPages&&$page>$maxPages)break; $rows=$this->get('products',['status'=>'publish','page'=>$page,'per_page'=>min(100,max(10,$perPage)),'orderby'=>'id','order'=>'asc']); if(!$rows)break; foreach($rows as $raw){if(empty($raw['id']))continue; [$p,$new,$v,$m]=$this->upsertProduct($raw); $new?$created++:$updated++;$variants+=$v;$media+=$m;} if(count($rows)<$perPage)break;} return compact('created','updated','variants','media'); }
 private function upsertProduct(array $r): array {return DB::connection('priyasa')->transaction(function()use($r){$eid=(string)$r['id'];$p=Product::where('source','woocommerce')->where('external_id',$eid)->first();$new=!$p;$p??=new Product();$p->source='woocommerce';$p->external_id=$eid;$p->name=strip_tags((string)$r['name']);$p->slug=$this->uniqueSlug(Str::slug((string)($r['slug']??$r['name'])),$p->id);$p->description=(string)($r['description']??'')?:null;$p->short_description=(string)($r['short_description']??'')?:null;$p->sku=(string)($r['sku']??'')?:null;$p->mrp=$this->money($r['regular_price']??$r['price']);$p->price=$this->money($r['sale_price']??$r['price']??$r['regular_price']);$p->brand=(string)($r['brands'][0]['name']??'')?:null;$p->status='published';$p->published_at=$p->published_at??now();$p->media=$this->imageUrls($r['images']??[]);$cat=$this->firstCategory($r['categories']??[]);if($cat)$p->category_id=$cat->id;$p->attributes=(array)($r['attributes']??[]);$p->save();$m=0;foreach((array)($r['images']??[]) as $i=>$im){$id=(string)($im['id']??'');$q=$p->media()->where('source','woocommerce');if($id!=='')$q->where('external_id',$id);else $q->where('url',(string)($im['src']??''));$pm=$q->first()??new ProductMedia();$pm->product_id=$p->id;$pm->type='image';$pm->url=(string)($im['src']??$im['url']??'');$pm->alt_text=(string)($im['alt']??$r['name']);$pm->sort_order=$i;$pm->is_primary=$i===0;$pm->source='woocommerce';$pm->external_id=$id?:null;$pm->source_external_id=$eid;$pm->metadata=$im;$pm->save();$m++;}
$vcount=0;if(($r['type']??'')==='variable'){foreach((array)$this->get('products/'.$eid.'/variations',['per_page'=>100]) as $vr){$this->upsertVariant($p,$vr);$vcount++;}} else {if(!$p->sku){$p->sku='WOO-'.$eid;$p->save();}$this->upsertVariant($p,['id'=>$eid,'sku'=>$p->sku,'price'=>$r['price'],'regular_price'=>$r['regular_price'],'stock_quantity'=>$r['stock_quantity'],'manage_stock'=>$r['manage_stock'],'attributes'=>[],'image'=>$r['images'][0]??null]);$vcount=1;}return [$p,$new,$vcount,$m];});}
 private function upsertVariant(Product $p,array $r): void {$eid=(string)$r['id'];$v=ProductVariant::where('source','woocommerce')->where('external_id',$eid)->first()??new ProductVariant();$v->product_id=$p->id;$v->source='woocommerce';$v->external_id=$eid;$v->sku=(string)($r['sku']??'')?:'WOO-'.$p->external_id.'-'.$eid;$v->price=$this->nullableMoney($r['sale_price']??$r['price']);$v->mrp=$this->nullableMoney($r['regular_price']);$v->attributes=(array)($r['attributes']??[]);$v->size=$this->attributeValue($r,'size');$v->color=$this->attributeValue($r,'color');$v->image_url=(string)data_get($r,'image.src','')?:null;$v->is_active=true;$v->save();$inv=Inventory::firstOrCreate(['variant_id'=>$v->id],['quantity'=>0,'reserved_quantity'=>0,'low_stock_threshold'=>3]);if((bool)($r['manage_stock']??false)&&is_numeric($r['stock_quantity']??null)){ $target=max(0,(int)$r['stock_quantity']);$delta=$target-(int)$inv->quantity;if($delta!==0)app(InventoryService::class)->setQuantity($v,$target,'woocommerce_sync','woocommerce',$eid,['source'=>'woocommerce']); }}
 public function syncOrders(int $maxPages=10): array {$count=0;$created=0;$updated=0;for($page=1;$page<=$maxPages;$page++){ $rows=$this->get('orders',['page'=>$page,'per_page'=>100,'orderby'=>'id','order'=>'asc']);if(!$rows)break;foreach($rows as $r){if(empty($r['id']))continue;$new=$this->upsertOrder($r);$new?$created++:$updated++;$count++;}if(count($rows)<100)break;}return compact('count','created','updated');}
 public function upsertOrder(array $r): bool {return DB::connection('priyasa')->transaction(function()use($r){$eid=(string)$r['id'];$order=Order::where('source','woocommerce')->where('source_external_id',$eid)->first();$new=!$order;$customer=$this->customer($r);$order??=new Order();$order->customer_id=$customer->id;$order->source='woocommerce';$order->source_external_id=$eid;$order->order_number=$new?$this->uniqueOrderNumber((string)($r['number']??$eid)):$order->order_number;$incoming=$this->mapStatus((string)($r['status']??'pending')); $order->status=$new ? $this->mergeStatus((string)$order->status,$incoming) : $incoming;$order->currency=(string)($r['currency']??'INR');$order->subtotal=$this->money($r['total']??0)-$this->money($r['shipping_total']??0)-$this->money($r['total_tax']??0);$order->discount_total=$this->money($r['discount_total']??0);$order->tax_total=$this->money($r['total_tax']??0);$order->shipping_total=$this->money($r['shipping_total']??0);$order->grand_total=$this->money($r['total']??0);$order->payment_status=$this->paymentStatus($r);$order->payment_method=(string)($r['payment_method']??'')?:null;$order->metadata=array_merge((array)$order->metadata,['woocommerce'=>$r]);$order->placed_at=$order->placed_at??now();$order->save();$this->address($customer,$r['shipping']??$r['billing']??[],$order);if($new){foreach((array)($r['line_items']??[]) as $line){$v=$this->variantBySku((string)($line['sku']??''));if(!$v)continue;$order->items()->create(['variant_id'=>$v->id,'sku'=>$v->sku,'product_name'=>strip_tags((string)($line['name']??$v->product->name)),'variant_label'=>null,'quantity'=>(int)($line['quantity']??1),'unit_price'=>$this->money($line['subtotal']??0)/max(1,(int)($line['quantity']??1)),'tax_amount'=>$this->money($line['total_tax']??0),'line_total'=>$this->money($line['total']??0),'snapshot'=>['source'=>'woocommerce','external_id'=>$line['id']??null]]);}}return $new;});}
 private function customer(array $r): Customer {$b=(array)($r['billing']??[]);$phone=$this->phone($b['phone']??null);$email=trim((string)($b['email']??''));$q=Customer::query();if($phone)$q->where('phone',$phone);elseif($email)$q->where('email',$email);$c=$q->first()??Customer::where('source','woocommerce')->where('external_id',(string)($r['customer_id']??''))->first();$c??=new Customer();$c->source='woocommerce';$c->external_id=(string)($r['customer_id']??$r['id']);$c->phone=$phone;$c->email=$email?:null;$c->first_name=trim((string)($b['first_name']??''))?:null;$c->last_name=trim((string)($b['last_name']??''))?:null;$c->save();return $c;}
 private function address(Customer $c,array $a,Order $o):void {if(!$a)return;$ad=Address::firstOrNew(['customer_id'=>$c->id,'line1'=>(string)($a['address_1']??''),'postal_code'=>(string)($a['postcode']??'')]);$ad->recipient_name=trim((string)($a['first_name']??'').' '.(string)($a['last_name']??''))?:($c->first_name.' '.$c->last_name);$ad->phone=$this->phone($a['phone']??$c->phone);$ad->line1=(string)($a['address_1']??'');$ad->line2=(string)($a['address_2']??'')?:null;$ad->city=(string)($a['city']??'');$ad->state=(string)($a['state']??'');$ad->postal_code=(string)($a['postcode']??'');$ad->country=strtoupper(substr((string)($a['country']??'IN'),0,2));$ad->save();$o->shipping_address_id=$ad->id;$o->save();}
 private function variantBySku(string $sku):?ProductVariant{return $sku!==''?ProductVariant::where('sku',$sku)->first():null;}
 private function firstCategory(array $cats):?Category {foreach($cats as $c){$name=trim((string)($c['name']??''));if($name==='')continue;$slug=Str::slug((string)($c['slug']??$name));return Category::firstOrCreate(['slug'=>$slug],['name'=>$name,'is_active'=>true]);}return null;}
 private function uniqueSlug(string $slug,?int $id):string {$base=$slug?:'product';$s=$base;$i=2;while(Product::where('slug',$s)->when($id,fn($q)=>$q->where('id','!=',$id))->exists())$s=$base.'-'.$i++;return $s;}
 private function uniqueOrderNumber(string $n):string {$base='WOO-'.$n;$s=$base;$i=2;while(Order::where('order_number',$s)->exists())$s=$base.'-'.$i++;return $s;}
 private function attributeValue(array $r,string $name):?string {foreach((array)($r['attributes']??[]) as $a)if(strtolower((string)($a['name']??$a['slug']??''))===strtolower($name))return (string)($a['option']??'');return null;}
 private function imageUrls(array $a):array{return array_values(array_unique(array_filter(array_map(fn($x)=>(string)($x['src']??$x['url']??''),$a))));}
 private function money($v):float{return is_numeric($v)?max(0,(float)$v):0.0;} private function nullableMoney($v):?float{return ($v===null||$v==='')?null:$this->money($v);} private function phone($v):?string{$s=preg_replace('/\D+/','',(string)$v);if($s==='')return null;if(strlen($s)===12&&str_starts_with($s,'91'))return '+'.$s;return strlen($s)===10?'+91'.$s:(strlen($s)>10?'+'.$s:null);} private function mapStatus(string $s):string{return match($s){'pending'=> 'pending_payment','processing','on-hold'=>'processing','completed'=>'delivered','cancelled','refunded','failed'=> 'cancelled','draft'=> 'pending_payment',default=>'processing'};} private function mergeStatus(string $current,string $incoming):string { if($current==='')return $incoming; if(in_array($incoming,['cancelled','refunded'],true))return $incoming; $rank=['pending_payment'=>0,'payment_failed'=>0,'confirmed'=>1,'processing'=>2,'packed'=>3,'shipped'=>4,'in_transit'=>5,'out_for_delivery'=>6,'delivered'=>7,'return_requested'=>8,'returned'=>9,'refunded'=>10]; return (($rank[$incoming]??2) >= ($rank[$current]??0)) ? $incoming : $current; }
 private function paymentStatus(array $r):string{return match((string)($r['status']??'')){ 'completed'=>'paid','refunded'=>'refunded','failed'=>'failed','cancelled'=>'cancelled',default=>'pending'};}
}
