<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
    protected $connection = 'priyasa'; public function up():void {
 if(!Schema::connection('priyasa')->hasColumn('priyasa_returns','customer_note')) Schema::connection('priyasa')->table('priyasa_returns',fn(Blueprint $t)=>$t->text('customer_note')->nullable());
 if(!Schema::connection('priyasa')->hasColumn('priyasa_returns','refund_amount')) Schema::connection('priyasa')->table('priyasa_returns',fn(Blueprint $t)=>$t->decimal('refund_amount',12,2)->default(0));
 if(!Schema::connection('priyasa')->hasColumn('priyasa_returns','admin_note')) Schema::connection('priyasa')->table('priyasa_returns',fn(Blueprint $t)=>$t->text('admin_note')->nullable());
 if(!Schema::connection('priyasa')->hasColumn('priyasa_returns','metadata')) Schema::connection('priyasa')->table('priyasa_returns',fn(Blueprint $t)=>$t->json('metadata')->nullable());
 if(Schema::connection('priyasa')->hasTable('priyasa_refunds') && !Schema::connection('priyasa')->hasColumn('priyasa_refunds','return_id')) Schema::connection('priyasa')->table('priyasa_refunds',fn(Blueprint $t)=>$t->foreignId('return_id')->nullable()->after('payment_id')->constrained('priyasa_returns')->nullOnDelete());
 if(!Schema::connection('priyasa')->hasTable('priyasa_return_items')) Schema::connection('priyasa')->create('priyasa_return_items',function(Blueprint $t){$t->id();$t->foreignId('return_id')->constrained('priyasa_returns')->cascadeOnDelete();$t->foreignId('order_item_id')->constrained('priyasa_order_items')->restrictOnDelete();$t->unsignedInteger('quantity');$t->decimal('refund_amount',12,2)->default(0);$t->string('reason')->nullable();$t->json('metadata')->nullable();$t->timestamps();$t->unique(['return_id','order_item_id']);});
 if(!Schema::connection('priyasa')->hasTable('priyasa_invoices')) Schema::connection('priyasa')->create('priyasa_invoices',function(Blueprint $t){$t->id();$t->foreignId('order_id')->unique()->constrained('priyasa_orders')->cascadeOnDelete();$t->string('invoice_number',64)->unique();$t->string('status',24)->default('issued');$t->string('currency',3)->default('INR');$t->decimal('subtotal',12,2)->default(0);$t->decimal('discount_total',12,2)->default(0);$t->decimal('taxable_total',12,2)->default(0);$t->decimal('tax_total',12,2)->default(0);$t->decimal('shipping_total',12,2)->default(0);$t->decimal('grand_total',12,2)->default(0);$t->string('seller_gstin',32)->nullable();$t->string('seller_state',64)->nullable();$t->json('billing_address')->nullable();$t->json('shipping_address')->nullable();$t->json('lines')->nullable();$t->timestamp('issued_at')->nullable();$t->timestamps();$t->index(['status','issued_at']);});
 } public function down():void {Schema::connection('priyasa')->dropIfExists('priyasa_invoices'); Schema::connection('priyasa')->dropIfExists('priyasa_return_items');} };
