<?php
namespace Modules\PriyasaCore\Http\Controllers\Webhooks;
use Illuminate\Http\Request; use Illuminate\Routing\Controller; use Modules\PriyasaCore\Models\CommerceConversation; use Modules\PriyasaCore\Models\CommerceConversationMessage; use Modules\PriyasaCore\Models\WhatsAppWebhookEvent; use Modules\PriyasaCore\Services\CommerceAgentService; use Modules\PriyasaCore\Services\MetaWhatsAppService; use Modules\PriyasaCore\Jobs\SendWhatsAppMessage;
class MetaWhatsAppController extends Controller {
 public function verify(Request $r,MetaWhatsAppService $meta){$v=$meta->verify((string)$r->query('hub_mode'),(string)$r->query('hub_verify_token'),(string)$r->query('hub_challenge'));return $v===null?response('Forbidden',403):response($v);}
 public function receive(Request $r,MetaWhatsAppService $meta,CommerceAgentService $agent){$raw=$r->getContent();if(!$meta->validSignature($raw,(string)$r->header('X-Hub-Signature-256')))return response()->json(['message'=>'Invalid signature'],401);$payload=$r->json()->all();$count=0;
  foreach(($payload['entry']??[]) as $entry) foreach(($entry['changes']??[]) as $change){$value=$change['value']??[];
   foreach(($value['statuses']??[]) as $status){$id=(string)($status['id']??'');if($id==='')continue;$eventId='status:'.$id.':'.($status['status']??'unknown');$event=WhatsAppWebhookEvent::firstOrCreate(['delivery_id'=>$eventId],['event_id'=>$id,'event_type'=>'message.status','status'=>$status['status']??null,'occurred_at'=>isset($status['timestamp'])?date('Y-m-d H:i:s',(int)$status['timestamp']):now(),'payload'=>$status,'processed_at'=>now()]); if($event->wasRecentlyCreated){$message=CommerceConversationMessage::where('provider_message_id',$id)->first(); if($message){$metadata=is_array($message->metadata)?$message->metadata:(json_decode((string)$message->metadata,true)?:[]); $message->update(['provider_status'=>$status['status']??null,'metadata'=>array_merge($metadata,['status_event'=>$status])]);}$count++;}}
   foreach(($value['messages']??[]) as $msg){$id=$msg['id']??null;if(!$id)continue;$event=WhatsAppWebhookEvent::firstOrCreate(['delivery_id'=>$id],['event_id'=>$id,'event_type'=>$msg['type']??'message','payload'=>$msg]);if(!$event->wasRecentlyCreated)continue;$phone=(string)($msg['from']??'');$text=(string)($msg['text']['body']??''); if(($msg['type']??'')==='interactive'){$text=(string)($msg['interactive']['button_reply']['title']??$msg['interactive']['list_reply']['title']??$msg['interactive']['button_reply']['id']??$msg['interactive']['list_reply']['id']??'');} if($phone&&$text!==''){$result=$agent->handle('whatsapp',$phone,$text,null);$out=CommerceConversationMessage::where('conversation_id',$result['conversation_id'])->where('direction','outbound')->latest('id')->first();if($out)SendWhatsAppMessage::dispatch($out->id,$phone,$result['reply']);}$event->update(['processed_at'=>now()]);$count++;}
  } return response()->json(['received'=>true,'processed'=>$count]); }
}
